version: '3'
services:
  app:
    image: ecomerce-backend
    ports:
    - "8080:8080"
    depends_on:
    - mysql
  mysql:
    image: mysql-ecomerce
    container_name: mysql-ecomerce
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_ROOT_USER=root
     - MYSQL_ROOT_DB=full-stack-ecommerce